export enum Unit {
    Grams = 'g',
    Milliliters = 'ml',
    Teaspoons = 'tsp',
    Tablespoons = 'tbsp',
    Kilograms = 'kg',
    Pounds = 'lb',
    Ounces = 'oz',
    Pints = 'pint',
    Quarts = 'qt',
    FluidOunces = 'fl oz',
    Cup = 'cup',
    Pinch = 'pinch',
    Dash = 'dash',
    Each = 'each',
    Count = 'count',
    Slice = 'slice',
    Clove = 'clove',
    Head = 'head',
}
