services:
    db:
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=test123
            - POSTGRES_DB=personal-cookbook
        networks:
            - personal-cookbook-network
        volumes:
            - personal-cookbook-data:/var/lib/postgresql/data

    scraper-api:
        build:
            context: ./backend/fastapi-recipe-scraper
        ports:
            - 8000:8000
        networks:
            - personal-cookbook-network

    api:
        build:
            context: ./backend/personal-cookbook-backend
        env_file: ./backend/personal-cookbook-backend/.env
        network_mode: service:frontend
        depends_on:
            - db
            - scraper-api

    frontend:
        build:
            context: ./frontend/personal-cookbook-frontend
        env_file: ./frontend/personal-cookbook-frontend/.env
        ports:
            # host:container
            - 80:80
            - 3000:3000
        networks:
            - personal-cookbook-network
        # links:
        #     - 'api:backend'
        develop:
            watch:
                - action: rebuild
                  path: frontend/personal-cookbook-frontend/src/app
                  target: /usr/src/app

networks:
    personal-cookbook-network:
        driver: bridge

volumes:
    personal-cookbook-data:
        driver: local
