services:
    db:
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=test123
            - POSTGRES_DB=personal-cookbook
        volumes:
            - personal-cookbook-data:/var/lib/postgresql/data

    scraper-api:
        build:
            context: ./backend/fastapi-recipe-scraper
        ports:
            - 3001:8000

    api:
        build:
            context: ./backend/personal-cookbook-backend
        # env_file: ./backend/personal-cookbook-backend/.env
        environment:
            - DB_HOST=db
            - SCRAPER_API_HOST=scraper-api
            - DB_PORT=5432
            - DB_USER=postgres
            - DB_PASSWORD=test123
            - DB_NAME=personal-cookbook
        ports:
            - 3002:3000
        depends_on:
            - db
            - scraper-api

    frontend:
        build:
            context: ./frontend/personal-cookbook-frontend
        # env_file: ./frontend/personal-cookbook-frontend/.env
        environment:
            - VITE_API_HOST=api
            - VITE_API_URL=http://${VITE_API_HOST}:8888
            - PORT=80
            - HOST=frontend
        ports:
            # host:container
            - 3003:80
        develop:
            watch:
                - action: rebuild
                  path: frontend/personal-cookbook-frontend/src/app
                  target: /usr/src/app

volumes:
    personal-cookbook-data:
        driver: local
